"""Domain: entities, enumerations, state machines, closed taxonomies (AD-27).

Imports nothing from `pm_ai` outside this package, which is what lets `ports`
express protocols in domain types without a cycle (AD-30).

These types exist because two independent reviewer runs found the same root
cause: words shared across components without a type behind them. Prose rules
did not fix it; a malformed reference is now a construction error rather than a
review comment.
"""

from pm_ai.domain.clocks import (
    EARLIEST_PLAUSIBLE,
    FUTURE_SKEW_TOLERANCE,
    ImplausibleTimestamp,
    due_date_basis,
    sweep_basis,
    validate_occurred_at,
)
from pm_ai.domain.disclosure import (
    DISCLOSURE_LEDGER_ARTIFACT,
    DISCLOSURE_LEDGER_PATH,
    DISCLOSURE_LEDGER_SCOPE,
    CommittedScopeLeak,
    DisclosureRecord,
    MalformedDisclosure,
    assert_writable,
    render_disclosure,
)
from pm_ai.domain.event_entries import (
    InconsistentVocabulary,
    LedgerCategory,
    SelfActionType,
    UnknownCategory,
    category,
)
from pm_ai.domain.events import (
    DecisionPayload,
    NormalizedEvent,
    ObservedEventType,
    PAYLOAD_FOR,
    PayloadMismatch,
    Provenance,
)
from pm_ai.domain.health import (
    Health,
    Probe,
    Report,
)
from pm_ai.domain.scope_model import (
    ARTIFACT_TIER,
    BACKUP_TARGETS,
    DIAGNOSTIC_ONLY,
    FOREIGN_ROOTS,
    REBUILD_TARGETS,
    RETENTION_MANAGED,
    SCOPE_TREES,
    Collection,
    Dir,
    File,
    MalformedLayout,
    OutsideTierModel,
    ScopeResolutionError,
    Tier,
)
from pm_ai.domain.storage_tiers import (
    CAPTURES,
    CAPTURE_STAGING,
    EVENT_LOG,
    GITIGNORE_FILENAME,
    ENCRYPTED,
    GITIGNORED,
    OPERATIONAL_DB,
    TierViolation,
    UnprotectedCaptureDir,
    assert_capture_dir_ignored,
    assert_capture_dir_untracked,
    gitignore_rule_for,
    requires_git_exclusion,
    assert_reindex_safe,
)
from pm_ai.domain.vcs import (
    GIT_SUBCOMMANDS,
    TrackingVerdict,
    UnpermittedGitSubcommand,
    VcsUnavailable,
)
from pm_ai.domain.identity import (
    PM_AI,
    PM_AI_ACTOR,
    UNRESOLVED,
    UNRESOLVED_ACTOR,
    Actor,
    DataScope,
    MalformedReference,
    NonDurableReferent,
    ScopeKind,
    SkillPermission,
    PM_AI_MINTED,
    SourceRef,
    TargetRef,
)
from pm_ai.domain.lifecycle import (
    DEFAULT_PROPOSAL_TTL,
    VERB_REGISTRY,
    CommitmentState,
    CoverageWindow,
    ProposalState,
    UnknownVerb,
    Verb,
    evaluate_commitment,
    lookup_verb,
)

__all__ = [
    "ARTIFACT_TIER",
    "Actor",
    "BACKUP_TARGETS",
    "CAPTURES",
    "CAPTURE_STAGING",
    "Collection",
    "CommitmentState",
    "CommittedScopeLeak",
    "CoverageWindow",
    "DEFAULT_PROPOSAL_TTL",
    "DIAGNOSTIC_ONLY",
    "DISCLOSURE_LEDGER_ARTIFACT",
    "DISCLOSURE_LEDGER_PATH",
    "DISCLOSURE_LEDGER_SCOPE",
    "DataScope",
    "DecisionPayload",
    "Dir",
    "DisclosureRecord",
    "EARLIEST_PLAUSIBLE",
    "ENCRYPTED",
    "EVENT_LOG",
    "EventEntry",
    "FOREIGN_ROOTS",
    "FUTURE_SKEW_TOLERANCE",
    "File",
    "GITIGNORED",
    "GITIGNORE_FILENAME",
    "GIT_SUBCOMMANDS",
    "Health",
    "ImplausibleTimestamp",
    "InconsistentVocabulary",
    "LedgerCategory",
    "MAX_ENTRY_LENGTH",
    "MalformedDisclosure",
    "MalformedEntry",
    "MalformedLayout",
    "MalformedReference",
    "NonDurableReferent",
    "NormalizedEvent",
    "OPERATIONAL_DB",
    "ObservedEventType",
    "OutsideTierModel",
    "PAYLOAD_FOR",
    "PM_AI",
    "PM_AI_ACTOR",
    "PM_AI_MINTED",
    "PayloadMismatch",
    "Probe",
    "ProposalState",
    "Provenance",
    "REBUILD_TARGETS",
    "RETENTION_MANAGED",
    "Report",
    "SCOPE_TREES",
    "SELF_ACTION_FIELDS",
    "ScopeKind",
    "ScopeResolutionError",
    "SelfActionType",
    "SkillPermission",
    "SourceRef",
    "TargetRef",
    "Tier",
    "TierViolation",
    "TrackingVerdict",
    "UNRESOLVED",
    "UNRESOLVED_ACTOR",
    "UnknownCategory",
    "UnknownVerb",
    "UnpermittedGitSubcommand",
    "UnprotectedCaptureDir",
    "VERB_REGISTRY",
    "VcsUnavailable",
    "Verb",
    "WRITER_OWNED_FIELDS",
    "assert_capture_dir_ignored",
    "assert_capture_dir_untracked",
    "assert_reindex_safe",
    "assert_writable",
    "category",
    "due_date_basis",
    "evaluate_commitment",
    "gitignore_rule_for",
    "lookup_verb",
    "render_disclosure",
    "render_entry",
    "render_value",
    "requires_git_exclusion",
    "scan_fields",
    "sweep_basis",
    "validate_occurred_at",
]
